name: mapsforge_flutter
description: A port of mapsforge for pure flutter. Show maps while the device is offline.
version: 2.0.2
# author: devemux86, mikes222
homepage: https://github.com/mikes222/mapsforge_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BSD License
  logging: ^1.0.2

  # BSD License
  convert: ^3.0.2

  # MIT License
  ecache: ^2.0.2
#    git:
#      url: https://github.com/mikes222/dcache
#    path: ../../github_ecache/

  # BSD License
  http: ^0.13.4

  # MIT License
  xml: ^6.1.0

  # Apache 2.0 License
  rxdart: ^0.27.4

  # BSD License
  synchronized: ^3.0.0+2

  # BSD License
  flutter_svg: ^1.1.0

  # BSD License
  #image: 2.1.13

  # BSD License, currently no WEB support
  path_provider: ^2.0.11

  # MIT License
  provider: ^6.0.3


  collection: ^1.16.0

  execution_queue: #^1.2.0
    path: ../../execution_queue.dart

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

#  assets:
#    - assets/defaultrender.xml
#    - assets/simplerender.xml
