name: mapsforge_flutter_rendertheme
resolution: workspace
description: Rendertheme implementation for mapsforge_flutter in DART.
homepage: https://github.com/mikes222/mapsforge_flutter
repository: https://github.com/mikes222/mapsforge_flutter
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:

  # Enhancement for collections
  collection: ^1.19.1

  # Workspace
  ecache: ^2.2.0

  logging: ^1.3.0

  # Workspace
  mapsforge_flutter_core: ^4.0.0


  # MIT License
  # for reading the rendertheme xml file
  # compatibility problems with flutter_svg
  xml: ^6.6.1


dev_dependencies:

  lints: ^6.0.0

  # BSD-3
  test: ^1.26.2