name: mapsforge_flutter_mapfile
resolution: workspace
description: Offline maps with pure flutter code. Provides rotation, markers, hillshading and much more.
homepage: https://github.com/mikes222/mapsforge_flutter
repository: https://github.com/mikes222/mapsforge_flutter
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:

  collection: ^1.19.1

  ecache: ^2.2.0

  logging: ^1.3.0

  # Workspace
  mapsforge_flutter_core: ^4.0.0

dev_dependencies:

  lints: ^6.0.0

  test: ^1.26.2
