name: globe_dem_converter
resolution: workspace
description: A command-line application to convert NOAA GLOBE DEM tiles into smaller lat/lon chunks.
publish_to: 'none'

version: 4.0.0

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  logging: ^1.3.0

  # Workspace
  mapsforge_flutter_core: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
